<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 text-capitalize">

                <div class="panel panel-primary">


                    <?php
                    echo($this->getChildHtml('items'));
                    echo $this->getChildHtml('items_grid');
                    ?>

                </div>
            </div>

            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 ">

                <div class="panel panel-success">
                    <div class="panel-heading">
                        <table class="panel-title">
                            <tbody>
                            <tr class="col-lg-12">
                                <td class="col-lg-4">Product</td>
                                <td class="col-lg-8">
                                    <form class="search-product">
                                        <input type="text" class="form-control" placeholder="Search">
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        </table>

                    </div>
                    <div class="panel-body product-panel">
                        <div class="row">
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3 hero-feature">
                                <div class="thumbnail">
                                    <img alt="" src="http://placehold.it/700x400"/>

                                    <div class="caption">
                                        <h5>
                                            Feature Label
                                        </h5>
                                    </div>
                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
