<div class="modal fade" id="modal-store-selector">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Store</h4>
            </div>
            <div class="modal-body body-store">

                <button type="button" class="btn-block btn btn-default" data-dismiss="modal">Store 1</button>
                <button type="button" class="btn-block btn btn-default" data-dismiss="modal">Store 1</button>
                <button type="button" class="btn-block btn btn-default" data-dismiss="modal">Store 1</button>
                <button type="button" class="btn-block btn btn-default" data-dismiss="modal">Store 1</button>
                <button type="button" class="btn-block btn btn-default" data-dismiss="modal">Store 1</button>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>