<script type="text/javascript">
    (function () {
        var isBootstrapEvent = false;
        if (window.jQuery) {
            var all = jQuery('*');
            jQuery.each(['hide.bs.dropdown',
                'hide.bs.collapse',
                'hide.bs.modal',
                'hide.bs.tooltip',
                'hide.bs.popover'], function (index, eventName) {
                all.on(eventName, function (event) {
                    isBootstrapEvent = true;
                });
            });
        }
        var originalHide = Element.hide;
        Element.addMethods({
            hide: function (element) {
                if (isBootstrapEvent) {
                    isBootstrapEvent = false;
                    return element;
                }
                return originalHide(element);
            }
        });
    })();
    $j(document).ready(function () {
        $j('#modal-store-selector').modal({
            'show': true,
        });
        $j('#modal-store-selector').on('hidden.bs.modal', function () {
            $j('#modal-customer-selector').modal({
                'show': true,
            });
        })
//        $j('.search-customer').keyup(function () {
//            $j('.body-customer').button('loading');
//            keyword=$j(this).val();
//            $j.ajax({
//                method:'post',
//                url:'<?php //echo Mage::helper('adminhtml')->getUrl('*/*/searchCustomer')?>//',
//                data: {customer:keyword},
////                dataTypes:'json'
//            }).success(function(data){
//                console.log(data);
//            });
////            $j.get("<?php ////echo Mage::helper('adminhtml')->getUrl('*/*/searchCustomer')?>////", {keyword: keyword}, function(data){console.log(data);});
////            setTimeout(function () {
////                $j('.body-customer').button('reset');
////            }, 1000);
//        });

    });
    var $stock_input = $j("#stock textarea");

    $stock_input.on("click", false);

    var countries = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        // url points to a json file that contains an array of country names, see
        // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
        prefetch: '<?php echo Mage::helper('adminhtml')->getUrl('*/*/searchCustomer')?>'
    });



    // passing in `null` for the `options` arguments will result in the default
    // options being used
    $j('.search-customer').typeahead(null, {
        name: 'countries',
        display: 'value',
        source: countries,
        templates: {
            empty: [
                '<div class="empty-message">',
                'unable to find any Best Picture winners that match the current query',
                '</div>'
            ].join('\n'),
            suggestion: Handlebars.compile('<div><strong>{{value}}</strong></div>')
        }
    });

</script>