<?php
$para  = $this->getParameter();
$class = strtolower(str_replace(' ', '', $para['label']));
?>
<div class="widget">
    <?php if ($para['show_label']): ?>
        <div class="widget-title">
            <h2><?php echo $para['label']; ?></h2>
        </div
    <?php endif ?>
</div>
<?php
    $_captionTransitions=[
        'L','R','T','B','TL','TR','BL','BR','WAVE|L','MCLIP|B'
    ];
?>
    <script>
    jQuery(document).ready(function ($) {
        var _CaptionTransitions = [];
        _CaptionTransitions["L"] = { $Duration: 800, x: 0.6, $Easing: { $Left: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["R"] = { $Duration: 800, x: -0.6, $Easing: { $Left: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["T"] = { $Duration: 800, y: 0.6, $Easing: { $Top: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["B"] = { $Duration: 800, y: -0.6, $Easing: { $Top: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["TL"] = { $Duration: 800, x: 0.6, y: 0.6, $Easing: { $Left: $JssorEasing$.$EaseInOutSine, $Top: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["TR"] = { $Duration: 800, x: -0.6, y: 0.6, $Easing: { $Left: $JssorEasing$.$EaseInOutSine, $Top: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["BL"] = { $Duration: 800, x: 0.6, y: -0.6, $Easing: { $Left: $JssorEasing$.$EaseInOutSine, $Top: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };
        _CaptionTransitions["BR"] = { $Duration: 800, x: -0.6, y: -0.6, $Easing: { $Left: $JssorEasing$.$EaseInOutSine, $Top: $JssorEasing$.$EaseInOutSine }, $Opacity: 2 };

        _CaptionTransitions["WAVE|L"] = { $Duration: 1500, x: 0.6, y: 0.3, $Easing: { $Left: $JssorEasing$.$EaseLinear, $Top: $JssorEasing$.$EaseInWave }, $Opacity: 2, $Round: { $Top: 2.5} };
        _CaptionTransitions["MCLIP|B"] = { $Duration: 600, $Clip: 8, $Move: true, $Easing: $JssorEasing$.$EaseOutExpo };

        var options = {
            $AutoPlay: <?php echo $para['auto']==0?"false":"true" ?>,                              //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
            $AutoPlayInterval: <?php echo $para['speed']==''?"false":$para['speed'] ?>,                       //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
            $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
            $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
            $UISearchMode: 0,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
            $CaptionSliderOptions: {                            //[Optional] Options which specifies how to animate caption
                $Class: $JssorCaptionSlider$,                   //[Required] Class to create instance to animate caption
                $CaptionTransitions: _CaptionTransitions,       //[Required] An array of caption transitions to play caption, see caption transition section at jssor slideshow transition builder
                $PlayInMode: 1,                                 //[Optional] 0 None (no play), 1 Chain (goes after main slide), 3 Chain Flatten (goes after main slide and flatten all caption animations), default value is 1
                $PlayOutMode: 3                                 //[Optional] 0 None (no play), 1 Chain (goes before main slide), 3 Chain Flatten (goes before main slide and flatten all caption animations), default value is 1
            },
            $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                $Loop: 1,                                       //[Optional] Enable loop(circular) of carousel or not, 0: stop, 1: loop, 2 rewind, default value is 1
                $SpacingX: 3,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                $SpacingY: 3,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                $DisplayPieces: 6,                              //[Optional] Number of pieces to display, default value is 1
                $ParkingPosition: 253,                          //[Optional] The offset position to park thumbnail,

                $ArrowNavigatorOptions: {
                    $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 6                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            }
        };

        var jssor_slider1<?php echo $class?> = new $JssorSlider$("slider1_container<?php echo $class?>", options);

        //responsive code begin
        //you can remove responsive code if you don't want the slider scales while window resizes
        function ScaleSlider() {
            var parentWidth = jssor_slider1<?php echo $class?>.$Elmt.parentNode.clientWidth;
            if (parentWidth)
                jssor_slider1<?php echo $class?>.$ScaleWidth(Math.min(parentWidth, <?php echo $para['width'] ?>));
            else
                window.setTimeout(ScaleSlider, 30);
        }
        ScaleSlider();

        $(window).bind("load", ScaleSlider);
        $(window).bind("resize", ScaleSlider);
        $(window).bind("orientationchange", ScaleSlider);
        //responsive code end
    });
</script>
<div id="slider1_container<?php echo $class?>" style="position: relative; width:720px;
        height: 380px; overflow: hidden; margin: 0 auto;">

    <!-- Loading Screen -->
    <div u="loading" style="position: absolute; top: 0px; left: 0px;">
        <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
        </div>
        <div style="position: absolute; display: block; background: url(<?php echo Mage::getBaseUrl('skin')?>/frontend/base/default/images/jssor/loading.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
        </div>
    </div>

    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 720px; height: 380px;
            overflow: hidden;">
        <?php


        $_sliders = $this->getSlider();
        $slides   = count($_sliders);
        ?>
        <?php foreach ($_sliders as $_slider):
        ?>
        <div>
            <a href="<?php echo $_slider->getUrl()?>">    
            <img u="image" src="<?php echo Mage::helper('widget_slider/image')->getBaseUrl() . '/' . $_slider->getImage() ?>"
                 alt="<?php echo $_slider->getTitle() ?>"
                 title="<?php echo $_slider->getTitle() ?>" /></a>
            <div u="caption" t="<?php echo $_captionTransitions[rand(0,9)] ?>" t2="<?php echo $_captionTransitions[rand(0,9)] ?>" style="position: absolute; top: 250px; left: 0px;
                    width: 600px; height: 50px;">
                <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        background-color: Black; opacity: 0.5; filter: alpha(opacity=50);">
                </div>
                <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        color: White; font-size: 16px; font-weight: bold; line-height: 50px; text-align: center;">
                    <?php echo $_slider->getTitle() ?>
                </div>
            </div>
            <img u="thumb" src="<?php echo Mage::helper('widget_slider/image')->getBaseUrl() . '/' . $_slider->getImage() ?>" />
        </div>
        <?php endforeach ?>
    </div>
    <style>
        .jssort07<?php echo $class?> {
            position: absolute;
            /* size of thumbnail navigator container */
            width: 800px;
            height: 100px;
        }

        .jssort07<?php echo $class?> .p {
            position: absolute;
            top: 0;
            left: 0;
            width: 99px;
            height: 66px;
        }

        .jssort07<?php echo $class?> .i {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 99px;
            height: 66px;
            filter: alpha(opacity=80);
            opacity: .8;
        }

        .jssort07<?php echo $class?> .p:hover .i, .jssort07 .pav .i {
            filter: alpha(opacity=100);
            opacity: 1;
        }

        .jssort07<?php echo $class?> .o {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 97px;
            height: 64px;
            border: 1px solid #000;
            box-sizing: content-box;
            transition: border-color .6s;
            -moz-transition: border-color .6s;
            -webkit-transition: border-color .6s;
            -o-transition: border-color .6s;
        }

        .jssort07<?php echo $class?> .pav .o {
            border-color: #0099ff;
        }

        .jssort07<?php echo $class?> .p:hover .o {
            border-color: #fff;
            transition: none;
            -moz-transition: none;
            -webkit-transition: none;
            -o-transition: none;
        }

        .jssort07<?php echo $class?> .p.pdn .o {
            border-color: #0099ff;
        }

        * html .jssort07<?php echo $class?> .o {
            /* ie quirks mode adjust */
            width /**/: 99px;
            height /**/: 66px;
        }
    </style>
    <!-- thumbnail navigator container -->
    <div u="thumbnavigator" class="jssort07<?php echo $class?>" style="width: 720px; height: 100px; left: 0px; bottom: 0px;">
        <!-- Thumbnail Item Skin Begin -->
        <div u="slides" style="cursor: default;">
            <div u="prototype" class="p">
                <div u="thumbnailtemplate" class="i"></div>
                <div class="o"></div>
            </div>
        </div>
        <!-- Thumbnail Item Skin End -->
        <style>
            .jssora11l<?php echo $class?>, .jssora11r<?php echo $class?> {
                display: block;
                position: absolute;
                /* size of arrow element */
                width: 37px;
                height: 37px;
                cursor: pointer;
                background: url(<?php echo Mage::getBaseUrl('skin')?>/frontend/base/default/images/jssor/a11.png) no-repeat;
                overflow: hidden;
            }

            .jssora11l<?php echo $class?> {
                background-position: -11px -41px;
            }

            .jssora11r<?php echo $class?> {
                background-position: -71px -41px;
            }

            .jssora11l<?php echo $class?> :hover {
                background-position: -131px -41px;
            }

            .jssora11r<?php echo $class?> :hover {
                background-position: -191px -41px;
            }

            .jssora11l<?php echo $class?>.jssora11ldn {
                background-position: -251px -41px;
            }

            .jssora11r<?php echo $class?>.jssora11rdn {
                background-position: -311px -41px;
            }
        </style>
        <!-- Arrow Left -->
            <span u="arrowleft" class="jssora11l<?php echo $class?>" style="top: 123px; left: 8px;">
            </span>
        <!-- Arrow Right -->
            <span u="arrowright" class="jssora11r<?php echo $class?>" style="top: 123px; right: 8px;">
            </span>
        <!--#endregion Arrow Navigator Skin End -->
    </div>
    <!--#endregion Thumbnail Navigator Skin End -->
</div>
<!-- Jssor Slider End -->